#!/bin/bash
#----------------------------------------------------------------------#
#                         * wallpaper-manger *                         #
#----------------------------------------------------------------------#

path="$(realpath "$1")"

if [ -z "$path" ] || [ ! -e "$path" ]; then
    notify-send -i /usr/share/icons/gnome/32x32/apps/preferences-desktop-wallpaper.png "w-m" "No picture selected"
    exit 1
fi

if gsettings get org.gnome.desktop.interface color-scheme | grep -q 'prefer-dark'; then 
    mode="-dark"
else
    mode=""
fi

if file -b --mime-type "$path" | grep -qE "image|xml"; then
   gsettings set org.gnome.desktop.background picture-uri"$mode" "file://$path"
   sh /usr/share/wallpaper_manager/w_m/actions/ir-prev.sh
   exit 0
	fi

	if
else
    notify-send -i /usr/share/icons/gnome/32x32/apps/preferences-desktop-wallpaper.png "w-m" "No picture"
    exit 1
fi
