#!/bin/sh
set -e

users=$( who | awk '{print $1}' | sed '/^root$/d' | uniq )
homedir="/home/$users"

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    killall -9 wm-app-indicador 2>/dev/null || true
fi

case "$1" in
    purge)
        if [ -d /usr/share/wallpaper_manager ]; then  
            rm -rf /usr/share/wallpaper_manager
        fi
        if [ -d "$homedir/.wallpaper_manager" ]; then  
            rm -rf "$homedir/.wallpaper_manager"
        fi
        if [ -f "$homedir/.config/autostart/wm-app-indicador.desktop" ]; then  
            rm "$homedir/.config/autostart/wm-app-indicador.desktop"
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Acciones para remove normal
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
