#!/bin/bash

if gsettings get org.gnome.desktop.interface color-scheme | grep -q 'prefer-dark'; then 
    mode="-dark"
    else
    mode=""
fi

DIR="$PWD"
FLAG="$HOME/.rotativo_en_marcha"

# evitar múltiples instancias
[ -f "$FLAG" ] && exit

touch "$FLAG"
STATE="$HOME/.imagen_actual.txt"

touch "$STATE"

# --- obtener imágenes ---
mapfile -t IMGS < <(find "$DIR" -type f \( -iname "*.jpg" -o -iname "*.png" \))

if [ ${#IMGS[@]} -eq 0 ]; then
    notify-send "Error" "No hay imágenes en $DIR"
    exit
fi

# --- zenity ---
TIME=$(zenity --scale \
  --title="Tiempo" \
  --text="Duración por fondo (minutos)" \
  --min-value=1 --max-value=120 --value=1)

[ $? -ne 0 ] && rm -f "$FLAG" && exit

TIME=$((TIME*60))

AUTOSTART="$HOME/.config/autostart/wallpaper-rotativo.desktop"
SCRIPT_PATH="$(realpath "$0")"

RESP=$(zenity --question \
  --title="Inicio automático" \
  --text="¿Arrancar rotación automáticamente al iniciar sesión?" \
  --ok-label="Sí" \
  --cancel-label="No"; echo $?)

if [ "$RESP" -eq 0 ]; then

    mkdir -p "$HOME/.config/autostart"

    cat > "$AUTOSTART" <<EOF
[Desktop Entry]
Type=Application
Exec=sh -c "sleep 10 && $SCRIPT_PATH"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Wallpaper Rotativo
Comment=Rotación automática de fondos
EOF

    notify-send "Wallpaper" "Se iniciará automáticamente al encender"

else
    rm -f "$AUTOSTART"
    notify-send "Wallpaper" "Inicio automático desactivado"
fi

MODO=$(zenity --list \
  --title="Modo" \
  --column="Modo" \
  "Random" \
  "Ordenado")

[ $? -ne 0 ] && rm -f "$FLAG" && exit

# --- índice ---
index=0

# --- loop ---
(
while true; do

  # cortar manual
  [ ! -f "$FLAG" ] && exit

  if [ "$MODO" = "Random" ]; then
    IMG="${IMGS[RANDOM % ${#IMGS[@]}]}"
  else
    IMG="${IMGS[$index]}"
    index=$(( (index+1) % ${#IMGS[@]} ))
  fi

  # aplicar fondo
  gsettings set org.gnome.desktop.background picture-uri"$mode" "file://$IMG"

  echo "$IMG" > "$STATE"

  # debug visible
  sh /usr/share/wallpaper_manager/w_m/actions/ir-prev.sh
  sh /usr/share/wallpaper_manager/w_m/actions/color-back1.sh
  sh /usr/share/wallpaper_manager/w_m/actions/color-back21.sh
  notify-send "Wallpaper" "$(basename "$IMG")"

  sleep "$TIME"

  # verificar si cambió
  CURRENT=$(gsettings get org.gnome.desktop.background picture-uri"$mode" | tr -d "'")
  CURRENT="${CURRENT#file://}"

  if [ "$CURRENT" != "$IMG" ]; then
      rm -f "$FLAG"
      exit
  fi

done
) &
